### ISSUE TITLE
ep3-bs Fehler bei der Installation im Zend Modul , brauche dringend Hilfe

### ISSUE THREAD

**Issue by azich01** [tkrebs/ep3-bs#226]
Fatal error: Uncaught Zend\Session\Exception\InvalidArgumentException: Invalid save_path provided; not writable in /var/www/html/vendor/zendframework/zend-session/src/Config/StandardConfig.php:232 Stack trace: #0 /var/www/html/vendor/zendframework/zend-session/src/Config/SessionConfig.php(233): Zend\Session\Config\StandardConfig->setSavePath('/var/www/html/d...') #1 /var/www/html/vendor/zendframework/zend-session/src/Config/StandardConfig.php(114): Zend\Session\Config\SessionConfig->setSavePath('/var/www/html/d...') #2 /var/www/html/vendor/zendframework/zend-session/src/Service/SessionConfigFactory.php(67): Zend\Session\Config\StandardConfig->setOptions(Array) #3 /var/www/html/vendor/zendframework/zend-session/src/Service/SessionConfigFactory.php(85): Zend\Session\Service\SessionConfigFactory->__invoke(Object(Zend\ServiceManager\ServiceManager), 'Zend\\Session\\Co...') #4 [internal function]: Zend\Session\Service\SessionConfigFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'zendsessionconf...', 'Zend\\S in /var/www/html/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 941

**Comment by azich01** [comment]
noch ein paar Infos
mysql-server 5.7.26-0ubuntu0 18.04.1
Apache2 2.4.10
zendframework 1.12.20+dfsg-1ubuntu1
php7.2.19-0ubuntu0-18-04-1

**Comment by tkrebs** [comment]
Zu diesem Problem gibt es bereits ein paar Themen mit Lösungsansätzen:

https://github.com/tkrebs/ep3-bs/issues?utf8=%E2%9C%93&q=save_path

**Comment by azich01** [comment]
danke
