### ISSUE TITLE
Layout ändern, wo?

### ISSUE THREAD

**Issue by adjustGirl** [tkrebs/ep3-bs#244]
Ich würde gern die Farben grundsätzlich ändern wollen und oben links ein Logo plazieren. Wo müsste ich das denn machen?

**Comment by tkrebs** [comment]
Schau mal hier:

https://bs.hbsys.de/documentation/de/installation/einrichtung/logo#docs

Und hier:

https://bs.hbsys.de/documentation/de/installation/einrichtung/farbschema#docs

**Comment by adjustGirl** [comment]
Danke. Aber mit der Registrierungsmaske (kompl. Adresse u. Fon) spielt unser Vorstand nicht mit! Hab es heute angesprochen. No way. Wo und wie kann man denn Felder eliminieren? In der registration.phtml geht das nicht, hab ich schon versucht. ;)

**Comment by adjustGirl** [comment]
Kann ich per PM kommunizieren? @tkrebs Und wie denn?

**Comment by adjustGirl** [comment]
Und wo kann man die Farbe für "belegt" von Grau z.Bsp. auf Rot ändern?

**Comment by tkrebs** [comment]
Alle Stil-Änderungen, inkl. der gewünschten Farbänderung, laufen über CSS:
https://bs.hbsys.de/documentation/de/installation/einrichtung/farbschema#docs

Die Felder der Registrierung könnten hier entfernt werden:
https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Form/RegistrationForm.php#L129

Sowie die dazugehörigen Validatoren:
https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Form/RegistrationForm.php#L458

Und die Verarbeitung im Controller:
https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Controller/AccountController.php#L168
(evtl. statt Entfernen auf einen leeren String setzen)

**Comment by adjustGirl** [comment]
Okay, vielen Dank. Jetzt habe ich noch bemerkt, dass der Filemanager nicht will. Bild hochladen, Upload wird mit OK quittiert, aber ... nix. Es rödelt nur .. Jetzt habe ich in den Folder per FTP das Bild gepackt. Wird aber nicht gezeigt. Mit den Rechten (bis 777) habe ich schon alles versucht. Und nun? @tkrebs ?

**Comment by adjustGirl** [comment]
> Die Felder der Registrierung könnten hier entfernt werden:
> https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Form/RegistrationForm.php#L129
> 
> Sowie die dazugehörigen Validatoren:
> https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Form/RegistrationForm.php#L458
> 
> Und die Verarbeitung im Controller:
> https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Controller/AccountController.php#L168
> (evtl. statt Entfernen auf einen leeren String setzen)

Hab ich jetzt gemacht und klappt auch ohne Fehlermeldungen. Wird auch ordentlich in die DB eingetragen. ABER! Es wird leider eine Aktivierungsmail OHNE den entsprechenden Link versandt. Hab auch nochmal auf Wiederholung geklickt. Wieder kein Link enthalten.

**Comment by tkrebs** [comment]
Der Aktivierungslink wird hier erstellt:

https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Controller/AccountController.php#L213

Und hier an die Aktivierungs-E-Mail angehangen:

https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Controller/AccountController.php#L218

Warum das in eurem Fall nicht funktioniert müsstet ihr im Detail debuggen.

**Comment by adjustGirl** [comment]
Gibts denn einen Debug Modus? @tkrebs

**Comment by Sahel2021** [comment]
Hallo. Wir wollen bei der Registrierung die Felder Straße und Hausnummer, Postleitzahl & Ort, Telefonnummer entfernen.
Version 1.7 PHP 7.4

Dazu habe ich wie oben angegeben folgende Zeilen auskommentiert:
1. https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Form/RegistrationForm.php#L129 
Zeile 129  /*        $this->add(array(
... bis ...
Zeile 188  'notes' => 'We only use this to inform you<br>about changes to your bookings',
            ),
        ));
*/
           
und https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Form/RegistrationForm.php#L458

Zeile 458  /*
			'rf-street' => array(
... bis ...
Zeile 616  'name' => 'Callback',
                        'options' => array(
                            'callback' => function($value) {
                                return $value === 'true';
                            },
                            'message' => 'Please agree to this',
                        ),
                        'break_chain_on_failure' => true,
                    ),
                ),
            ),
*/           

und in https://github.com/tkrebs/ep3-bs/blob/master/module/User/src/User/Controller/AccountController.php#L168
/*                $meta['street'] = $registrationData['rf-street'] . ' ' . $registrationData['rf-number'];
                $meta['zip'] = $registrationData['rf-zip'];
                $meta['city'] = $registrationData['rf-city'];
                $meta['phone'] = $registrationData['rf-phone'];
*/

bei Aufruf der Registrierung im Frontend kommt dann Fehlermeldung:
"No element by the name of [rf-street] found in form"
Exception details
Type
Zend\Form\Exception\InvalidElementException
Mitteilung
No element by the name of [rf-street] found in form
File
/www/htdocs/w008a823/ep3.nyanet.de/vendor/zendframework/zend-form/src/Fieldset.php:219
Stack trace
#0 /www/htdocs/w008a823/ep3.nyanet.de/module/User/view/user/account/registration.phtml(100): Zend\Form\Fieldset->get('rf-street')
#1 /www/htdocs/w008a823/ep3.nyanet.de/module/Zend/View/src/Renderer/PhpRenderer.php(506): include('/www/htdocs/w00...')
#2 /www/htdocs/w008a823/ep3.nyanet.de/module/Zend/View/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(NULL)
#3 /www/htdocs/w008a823/ep3.nyanet.de/module/Zend/View/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#4 /www/htdocs/w008a823/ep3.nyanet.de/module/Zend/View/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#5 /www/htdocs/w008a823/ep3.nyanet.de/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#6 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#7 /www/htdocs/w008a823/ep3.nyanet.de/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /www/htdocs/w008a823/ep3.nyanet.de/vendor/zendframework/zend-eventmanager/src/EventManager.php(248): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent))
#9 /www/htdocs/w008a823/ep3.nyanet.de/vendor/zendframework/zend-mvc/src/Application.php(384): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#10 /www/htdocs/w008a823/ep3.nyanet.de/vendor/zendframework/zend-mvc/src/Application.php(356): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#11 /www/htdocs/w008a823/ep3.nyanet.de/public/index.php(66): Zend\Mvc\Application->run()
#12 {main}

Wo liegt der Fehler? 
Wenn jemand funktionierende Dateien hat mit entfernten Felder der Registrierung, dann wäre ich dankbar. Kontakt mh@nyanet.de
