### ISSUE TITLE
Zend throws error when trying to make a periodic booking

### ISSUE THREAD

**Issue by Felixalsothecat** [tkrebs/ep3-bs#388]
Hello

We just installed ep-3 on PHP 7.2. So not sure whether it is an installation error.

If we try to do a periodic booking (daily, weekly etc) we get the below "invalid date range error"

Somebody else had this, too, but issue was closed without giving a solution.

Thank you for your help!

regards
Felixalsothecat

Exception details

Type

    InvalidArgumentException

Message

    Invalid date range passed for reservation creation

File

    /home/www/chaosep3/htdocs/module/Booking/src/Booking/Manager/ReservationManager.php:149

Stack trace

    #0 /home/www/chaosep3/htdocs/module/Backend/src/Backend/Controller/Plugin/Booking/Create.php(133): Booking\Manager\ReservationManager->createByRange(Object(Booking\Entity\Booking), Object(DateTime), Object(DateTime), '06:00', '10:00', 7)
    #1 [internal function]: Backend\Controller\Plugin\Booking\Create->__invoke(Object(User\Entity\User), '06:00', '10:00', Object(DateTime), Object(DateTime), 7, Object(Square\Entity\Square), 'pending', '1', '', 'Felix Muhlebach')
    #2 /home/www/chaosep3/htdocs/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(318): call_user_func_array(Object(Backend\Controller\Plugin\Booking\Create), Array)
    #3 /home/www/chaosep3/htdocs/module/Backend/src/Backend/Controller/BookingController.php(151): Zend\Mvc\Controller\AbstractController->__call('backendBookingC...', Array)
    #4 /home/www/chaosep3/htdocs/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Backend\Controller\BookingController->editAction()
    #5 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
    #6 /home/www/chaosep3/htdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #7 /home/www/chaosep3/htdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #8 /home/www/chaosep3/htdocs/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
    #9 /home/www/chaosep3/htdocs/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
    #10 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
    #11 /home/www/chaosep3/htdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #12 /home/www/chaosep3/htdocs/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #13 /home/www/chaosep3/htdocs/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
    #14 /home/www/chaosep3/htdocs/public/index.php(75): Zend\Mvc\Application->run()
    #15 {main}

© 2020 CHaOS Rowing (Imprint

**Comment by Felixalsothecat** [comment]
OK - solved it - error message could be a bit more telling - if you chose a repetiive booking the end date becomes editable. the end date refers to the last date the booking should be repeated. 

Would be great if per default the end date would be empty, and a mandatory field for repetitive bookings. Then idiots like me cannot do it wrong.
