### ISSUE TITLE
Buchungssystem funktioniert plötzlich nicht mehr

### ISSUE THREAD

**Issue by haGibear** [tkrebs/ep3-bs#400]
Scheinbar gibt es mit ZEND Probleme:
`Fatal error: Uncaught Zend\ModuleManager\Exception\RuntimeException: Module (index.php) could not be initialized. in /home/.sites/327/site3327867/web/tennis/vendor/zendframework/zend-modulemanager/src/ModuleManager.php:203 Stack trace: #0 /home/.sites/327/site3327867/web/tennis/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(175): Zend\ModuleManager\ModuleManager->loadModuleByName(Object(Zend\ModuleManager\ModuleEvent)) #1 /home/.sites/327/site3327867/web/tennis/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(97): Zend\ModuleManager\ModuleManager->loadModule('index.php') #2 [internal function]: Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent)) #3 /home/.sites/327/site3327867/web/tennis/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent)) #4 /home/.sites/327/site3327867/web/tennis/vendor/zendframework/zend-eventmanager/src/EventManager.php(248): Zend\EventManager\EventManager->trigger in /home/.sites/327/site3327867/web/tennis/vendor/zendframework/zend-modulemanager/src/ModuleManager.php on line 203`

Ich bin ziemlich ratlos. Habe schon die Verzeichnisse "vendor" und "module" neu hochgeladen, leider ohne Erfolg.
Der Webspace lief heute Morgen auf PHP 7.3, bin mir nicht sicher ob das automatisch vom Betreiber umgestellt wurde. Aber kann das die Installation zerschießen? Wechsel auf PHP 7.2 brachte auch nichts.

**Comment by haGibear** [comment]
Anmerkung:
Die Seite wird bei world4you gehostet. Ich habe nun eine neue Installation in einem anderen Verzeichnis ausgeführt, das System läuft auch dort nicht sauber (Layout komplett verzerrt, Fehlermeldungen).
