### ISSUE TITLE
Uncaught Error: Class 'Base\Manager\AbstractManagerInitializer' not found 

### ISSUE THREAD

**Issue by LuMpeH** [tkrebs/ep3-bs#438]
Hallo,

ich bekomme folgende Fehlermeldung, wenn ich eine Datei (z.B. setup.php) starten will:

`Fatal error: Uncaught Error: Class 'Base\Manager\AbstractManagerInitializer' not found in /var/www/htdocs/bookingTennis/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:365 Stack trace: #0 /var/www/htdocs/bookingTennis/vendor/zendframework/zend-servicemanager/src/Config.php(153): Zend\ServiceManager\ServiceManager->addInitializer('Base\\Manager\\Ab...') #1 /var/www/htdocs/bookingTennis/vendor/zendframework/zend-modulemanager/src/Listener/ServiceListener.php(223): Zend\ServiceManager\Config->configureServiceManager(Object(Zend\ServiceManager\ServiceManager)) #2 [internal function]: Zend\ModuleManager\Listener\ServiceListener->onLoadModulesPost(Object(Zend\ModuleManager\ModuleEvent)) #3 /var/www/htdocs/bookingTennis/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent)) #4 /var/www/htdocs/bookingTennis/vendor/zendframework/zend-eventmanager/src/EventManager.php(248): Zend\EventManager\EventManager->triggerListeners('loadModules.pos...', Object(Zen in /var/www/htdocs/bookingTennis/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 365
`

Mein Setup:
Ubuntu 18.04
PHP 7.4 (fpm)
Nginx

Ich denke ich habe soweit alles korrekt konfiguriert.

Jemand eine Idee, was ich probieren kann?

Ich habe 1:1 das gleiche gemacht wie auf meinem MacBook, wo ich XAMPP (PHP 7.4) installiert hab. Dort klappt es. Allerdings läuft da Apache...

Noch ein Auszug aus der Nginx conf:

> location ~ \.php(?:$|/) {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                fastcgi_param HTTPS on;
                fastcgi_param modHeadersAvailable true;
                fastcgi_pass 127.0.0.1:9000;
        }

**Comment by LuMpeH** [comment]
Ok, Kommando zurück. Mein FTP Programm hat wohl ein paar Dateien "vergessen" beim Upload. Es klappt jetzt. Kann zu hier 🙂.
