### ISSUE TITLE
Fehler bei der Einrichtung

### ISSUE THREAD

**Issue by Wibbinho** [tkrebs/ep3-bs#460]
Hallo zusammen,
ich habe nach eigentlich erfolgreicher Installation beim Aufrufen des Setups folgendes Problem:
Oops ... da ist wohl etwas schief gelaufen
System has already been setup
Exception details
Type
RuntimeException
Mitteilung
System has already been setup
File
/var/www/vhosts/hosting145919.a2e97.netcup.net/httpdocs/platzbuchung/module/Setup/src/Setup/Controller/Plugin/ValidateSetup.php:29
Stack trace
#0 [internal function]: Setup\Controller\Plugin\ValidateSetup->__invoke('index')
#1 /var/www/vhosts/hosting145919.a2e97.netcup.net/httpdocs/platzbuchung/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(318): call_user_func_array(Object(Setup\Controller\Plugin\ValidateSetup), Array)
#2 /var/www/vhosts/hosting145919.a2e97.netcup.net/httpdocs/platzbuchung/module/Setup/src/Setup/Controller/IndexController.php(15): Zend\Mvc\Controller\AbstractController->__call('validateSetup', Array)
#3 /var/www/vhosts/hosting145919.a2e97.netcup.net/httpdocs/platzbuchung/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(84): Setup\Controller\IndexController->indexAction()
#4 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#5 /var/www/vhosts/hosting145919.a2e97.netcup.net/httpdocs/platzbuchung/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#6 /var/www/vhosts/hosting145919.a2e97.netcup.net/httpdocs/platzbuchung/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /var/www/vhosts/hosting145919.a2e97.netcup.net/httpdocs/platzbuchung/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(116): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#8 /var/www/vhosts/hosting145919.a2e97.netcup.net/httpdocs/platzbuchung/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#9 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /var/www/vhosts/hosting145919.a2e97.netcup.net/httpdocs/platzbuchung/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#11 /var/www/vhosts/hosting145919.a2e97.netcup.net/httpdocs/platzbuchung/vendor/zendframework/zend-eventmanager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/vhosts/hosting145919.a2e97.netcup.net/httpdocs/platzbuchung/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#13 /var/www/vhosts/hosting145919.a2e97.netcup.net/httpdocs/platzbuchung/public/setup.php(66): Zend\Mvc\Application->run()
#14 {main}

**Comment by Wibbinho** [comment]
Leider habe ich recht wenig Ahnung von solchen Dingen und keine Ahnung was das bedeutet oder wie ich es lösen  kann! :)
Vielen Dank für eure Hilfe!

**Comment by cbits68** [comment]
Was heißt erfolgreiche Installation?
Offensichtlich ja wohl nicht erfolgreich ;-) Die Fehlermeldung weist ja erstmal darauf hin, dass das Setup bereits schon mal gelaufen ist. warum auch immer.
Es ist schwer Dir zu helfen, wenn man nicht weiß, was Du genau gemacht hast und wie Deine Installationsumgebung aussieht.

Das ist ungefähr so, als würdest Du in ein Automobilforum schreiben, Hilfe mein Auto springt nicht an, ich habe leider keine Ahnung von Autos aber wie bekomme ich das gelöst...

Also ohne weitere Infos wird es schwierig Dir zu helfen. Zumindest für mich ;-)

**Comment by Wibbinho** [comment]
Erfolgreiche Installation heißt für mich, dass bis dahin alles geklappt hat.
Sorry, dass ich von dieser Materie so wenig Ahnung habe.
Dachte halt anhand der Meldung könnten Profis schon erkennen was evtl.
schief läuft.
Welche Informationen würdest du denn zusätzlich benötigen?
Ich nutze netcup als webhost, PHP 7.4.
Wenn du weitere Infos benötigst, lass es mich wissen.
Ansonsten dennoch vielen Dank für dein Feedback.

Am So., 28. März 2021 um 23:06 Uhr schrieb anborn ***@***.***

**Comment by cbits68** [comment]
Laut install.txt in data/docs sind folgende Schritte erforderlich (einige auch optional):
Hast Du die Schritte 4 & 5 auch durchgeführt?

1. Setup the local configuration
   - rename   config/init.php.dist   to   init.php
   - optionally edit and customize the   init.php   values

   - rename   config/autoload/local.php.dist   to   local.php
   - edit the   local.php   and insert your database credentials

   - rename   public/.htaccess_original   to   .htaccess
     (if you experience webserver problems, try instead renaming   public/.htacess_alternative   to   .htaccess)

2. Enable (recursively) UNIX write permission for
   - data/cache/
   - data/log/
   - data/session/
   - public/docs-client/upload/
   - public/imgs-client/upload/

3. Setup the database by calling the setup.php

4. Delete the setup tool
   - public/setup.php

5. Delete any files in the following directory
   - data/cache/

6. Optionally customize public files
   - css-client/default.css (custom color scheme)
   - imgs-client/icons/fav.ico
   - imgs-client/layout/logo.png (75x75)

**Comment by cbits68** [comment]
oder rufst Du beim Aufruf der Seite immer noch das setup.php auf?
Dann könnte ich mir vorstellen, warum die Meldung kommt "System has already been setup"

**Comment by Wibbinho** [comment]
weder noch...habe alles entsprechend der install.txt. gemacht und auch die
schritte 4 & 5 ausgeführt.
wenn ich die index.php ausführe, sagt er:
Database required

Please setup the database prior to first usage

Use *Setup Tool* <http://www.wirbelwi.de/platzbuchung/public/setup.php/>

Am Mo., 29. März 2021 um 10:27 Uhr schrieb anborn ***@***.***

**Comment by cbits68** [comment]
Versuche doch einfach die Installation noch mal neu zu machen.
ep3 Verzeichnis löschen, neu hochladen, neue Datenbank und alles sauber in der init.php eintragen (Datenbank Zugriffsparameter). Danach das setup.php wieder ausführen. Am Besten Screenshots der einzelnen Schritte machen.
Für mich sieht es so aus, dass Du bei der Installation einen Fehler gemacht hast. Welchen kann ich Dir aber leider nicht sagen.

**Comment by cbits68** [comment]
Wenn Du, wie Du schreibst, keine Ahnung von den Dingen hast, warum versuchst Du es eigentlich?
Es gibt doch auch andere Möglichkeiten, ein Buchungssystem zu nutzen. kommerziell oder auch  kostenfrei über Initiativen wie "Vereine helfen Vereinen"
Die installieren entsprechende Systeme und bieten diese inkl. Hosting an. Dann bekommst Du einen Admin Zugriff und kannst alles Weitere in der SaaS Lösungen für Euch konfigurieren.
Ist vielleicht einfacher ;-)

**Comment by cbits68** [comment]
Vielleicht passen auch die Zugangsdaten zur DB in der lokalen.php nicht. Prüfe doch mal in der DB, ob die Tabellen überhaupt angelegt wurden.

**Comment by dschousef** [comment]
Der Fehler kommt mir bekannt vor. Den hatte ich damals bei der Einrichtung auch. Wohl deshalb, weil ich eine bestehende Datenbank, also keine leere verwendet hab. Deshalb hab ich in der ValidateSetup.php einfach den Wert von 0 auf 1000 erhöht:

                if ($res && count($res) > 1000) {
                    throw new \RuntimeException('System has already been setup');
