### ISSUE TITLE
Configuration required

### ISSUE THREAD

**Issue by KevinTauschnik** [tkrebs/ep3-bs#469]
Ich komme leider bei der Installation nicht weiter es wird mir die ganze Zeit angezeigt
Please provide database configuration prior to first usage in file config/autoload/local.php
(Arbeite mit dem Ubuntu Server 20.04 LTS ohne GUI)

**Comment by cbits68** [comment]
Sieht nach einem Problem mit dem Zugriff auf die Datenbank aus. Hast Du mal probiert, ob Du manuell vom Server auf die Datenbank kommst?

**Comment by KevinTauschnik** [comment]
Es wird noch nicht einmal Tabellen erstellt, die Datenbank wurde allerdings in MariaDB erstellt. Auch ein User wurde angelegt, bin leider nicht ganz fit, brauche das aber für mein Abschlussprojekt. Gibt es einen Lösungsweg wenn es um den Zugang geht ?

**Comment by cbits68** [comment]
MariaDB ist auch über Port 3306 auf dem Server erreichbar?

**Comment by KevinTauschnik** [comment]
Okay es wurde jetzt mit dem Setup.php tolol eingerichtet nach der einrichtung kommtder Fehler :

Fatal error: Uncaught Zend\Session\Exception\InvalidArgumentException: Invalid save_path provided; not writable in /var/www/html/booking/vendor/zendframework/zend-session/src/Config/StandardConfig.php:232 Stack trace: #0 /var/www/html/booking/vendor/zendframework/zend-session/src/Config/SessionConfig.php(233): Zend\Session\Config\StandardConfig->setSavePath() #1 /var/www/html/booking/vendor/zendframework/zend-session/src/Config/StandardConfig.php(114): Zend\Session\Config\SessionConfig->setSavePath() #2 /var/www/html/booking/vendor/zendframework/zend-session/src/Service/SessionConfigFactory.php(67): Zend\Session\Config\StandardConfig->setOptions() #3 /var/www/html/booking/vendor/zendframework/zend-session/src/Service/SessionConfigFactory.php(85): Zend\Session\Service\SessionConfigFactory->__invoke() #4 [internal function]: Zend\Session\Service\SessionConfigFactory->createService() #5 /var/www/html/booking/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(934): call_user_func() #6 /var/www/html/booking/vendor in /var/www/html/booking/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 941

**Comment by cbits68** [comment]
Invalid save_path provided; not writable in /var/www/html/booking/vendor/zendframework/zend-session/src/Config/StandardConfig.php
Möglicherweise fehlende Schreibrechte in var/www?
vielleicht stimmt auch was mit der apache konfig nicht, oder was nutzt Du als Webserver?

**Comment by cbits68** [comment]
welche PHP Version ist denn auf Deinem System aktiv?

**Comment by scurth** [comment]
> Ich komme leider bei der Installation nicht weiter es wird mir die ganze Zeit angezeigt
> Please provide database configuration prior to first usage in file config/autoload/local.php
> (Arbeite mit dem Ubuntu Server 20.04 LTS ohne GUI)

Die Fehlermeldung ist Irre führend. Wenn die DB nicht erreicht werden kann wird behauptet das die local.php angepasst werden muss. In der php.ini muss die mysql dbo erweiterung aktiviert werden.

**Comment by MaxSPG** [comment]
Danke @scurth, der letzte Kommentar hat mir etwas weitergeholfen! 😃

Hatte das gleiche Problem wie der initiale Poster, dass (trotz sonstiger korrekter config) immer wieder die Fehlermeldung kam, dass `local.php` angepasst werden müsse - was jedoch bereits geschehen war.
Wenn ich `/setup.php/` aufgerufen hatte, kam zudem ein 500er Error (sichtbar im Network Tab des Browser Dev Modes).

Weitere Infos für Leute mit dem gleichen Problem:
- Die php.ini Datei ist meist unter `etc/php/<your-version>` zu finden.
- öffnet es mit vim und sucht mit `/` nach "extension"
- entfernt die Kommentare (semicolons) vor "mysqli" und "pdo_mysql"

Zudem Vorsicht (steht nicht in der Dokumentation 🫠):
Beim installieren von PHP müssen dann auch gleich noch die extensions "mysqli" und "pdo-mysql" installiert werden.

-> Das geht wie folgt:
`sudo apt install php8.1 php8.1-intl php8.1-mysqli php8.1-pdo-mysql`

---

Ausserdem müssen die Zugriffsrechte für die in der Dokumentation genannten Ordner für den apache2 webserver gesetzt werden, was bedeutet dass die Kommandos wie folgt ausgeführt werden müssen:
`sudo chown -R www-data:www-data data/cache/`
etc.

Erst danach hat bei mir alles geklappt. ✌🏻
(PHP 8.1)
