### ISSUE TITLE
Die Namen der anderen Spieler sind optional

### ISSUE THREAD

**Issue by OlliHe** [tkrebs/ep3-bs#585]
Hallo, 

ich habe bei jedem Tennisplatz di Angabe der Mitspieler als Optional angegeben. Wenn bei der Buchung jetzt kein Spieler angegeben wird, kommt folgende Fehlermeldung:

_Oops ... da ist wohl etwas schief gelaufen
Die vollständigen Vor- und Nachnamen der anderen Spieler sind erforderlich

Bitte [informieren Sie uns](https://www.tc-weinboehla.de/index.php/kontakt/) bei exotischen oder nicht nachvollziehbaren Fehlermeldungen,
damit wir das Problem schnell beheben können.
[Zurück zur Startseite](https://wm1v4gg35.homepage.t-online.de/buchungssystem/public/)
Exception details

Type

    RuntimeException

Mitteilung

    Die <b>vollständigen Vor- und Nachnamen</b> der anderen Spieler sind erforderlich

File

    /home/www/public_html/buchungssystem/module/Square/src/Square/Controller/BookingController.php:140

Stack trace

    #0 /home/www/public_html/buchungssystem/src/Zend/Mvc/src/Controller/AbstractActionController.php(84): Square\Controller\BookingController->confirmationAction()
    #1 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch()
    #2 /home/www/public_html/buchungssystem/src/Zend/EventManager/src/EventManager.php(490): call_user_func()
    #3 /home/www/public_html/buchungssystem/src/Zend/EventManager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners()
    #4 /home/www/public_html/buchungssystem/src/Zend/Mvc/src/Controller/AbstractController.php(116): Zend\EventManager\EventManager->triggerEventUntil()
    #5 /home/www/public_html/buchungssystem/src/Zend/Mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch()
    #6 [internal function]: Zend\Mvc\DispatchListener->onDispatch()
    #7 /home/www/public_html/buchungssystem/src/Zend/EventManager/src/EventManager.php(490): call_user_func()
    #8 /home/www/public_html/buchungssystem/src/Zend/EventManager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners()
    #9 /home/www/public_html/buchungssystem/src/Zend/Mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil()
    #10 /home/www/public_html/buchungssystem/public/index.php(66): Zend\Mvc\Application->run()
    #11 {main}_

Was muss ich ändern, dass hier auch optional möglich ist?

Danke euch und Gruß
Olli

**Comment by OlliHe** [comment]
Hab es gefunden. Sorry für den Datenmüll. 

;-)
Gruß
Olli
