### ISSUE TITLE
Anmeldung am System ist nicht mehr möglich

### ISSUE THREAD

**Issue by tennstar1** [tkrebs/ep3-bs#597]
Hallo,
mein System läuft seit mehreren Jahren Problemlos und ich habe es nach erscheinen des Updates 1.8.1 auf diesen Stand gebracht und bei IONOS auf PHP 8.1.umgestellt. Nach dem Start schien alles problemlos zu funktionieren, jetzt aber wollte sich ein Teilnehmer neu anmelden und dieses funktioniert nun nicht mehr!
Entweder es erscheint immer wieder die Fehlermeldung "Diese EMail Adresse ist schon registriert" obwohl diese im System nicht registriert ist. 
Auch folgende folgende Fehlermeldung ist erfolgt:
`Type
Error
Mitteilung
Class "TrueBV\Punycode" not found
File
/homepages/20/d34594934/htdocs/tgpbs/src/Zend/Mail/src/Header/AbstractAddressList.php:119
Stack trace
#0 /homepages/20/d34594934/htdocs/tgpbs/src/Zend/Mail/src/Header/AbstractAddressList.php(150): Zend\Mail\Header\AbstractAddressList->idnToAscii()
#1 /homepages/20/d34594934/htdocs/tgpbs/src/Zend/Mail/src/Transport/Sendmail.php(169): Zend\Mail\Header\AbstractAddressList->getFieldValue()
#2 /homepages/20/d34594934/htdocs/tgpbs/src/Zend/Mail/src/Transport/Sendmail.php(120): Zend\Mail\Transport\Sendmail->prepareRecipients()
#3 /homepages/20/d34594934/htdocs/tgpbs/module/Base/src/Base/Service/MailService.php(53): Zend\Mail\Transport\Sendmail->send()
#4 /homepages/20/d34594934/htdocs/tgpbs/module/Base/src/Base/Service/MailService.php(77): Base\Service\MailService->send()
#5 /homepages/20/d34594934/htdocs/tgpbs/module/Base/src/Base/Service/MailService.php(89): Base\Service\MailService->sendWithAttachments()
#6 /homepages/20/d34594934/htdocs/tgpbs/module/User/src/User/Service/MailService.php(39): Base\Service\MailService->sendPlain()
#7 /homepages/20/d34594934/htdocs/tgpbs/module/User/src/User/Controller/AccountController.php(222): User\Service\MailService->send()
#8 /homepages/20/d34594934/htdocs/tgpbs/src/Zend/Mvc/src/Controller/AbstractActionController.php(84): User\Controller\AccountController->registrationAction()
#9 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch()
#10 /homepages/20/d34594934/htdocs/tgpbs/src/Zend/EventManager/src/EventManager.php(490): call_user_func()
#11 /homepages/20/d34594934/htdocs/tgpbs/src/Zend/EventManager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners()
#12 /homepages/20/d34594934/htdocs/tgpbs/src/Zend/Mvc/src/Controller/AbstractController.php(116): Zend\EventManager\EventManager->triggerEventUntil()
#13 /homepages/20/d34594934/htdocs/tgpbs/src/Zend/Mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch()
#14 [internal function]: Zend\Mvc\DispatchListener->onDispatch()
#15 /homepages/20/d34594934/htdocs/tgpbs/src/Zend/EventManager/src/EventManager.php(490): call_user_func()
#16 /homepages/20/d34594934/htdocs/tgpbs/src/Zend/EventManager/src/EventManager.php(260): Zend\EventManager\EventManager->triggerListeners()
#17 /homepages/20/d34594934/htdocs/tgpbs/src/Zend/Mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil()
#18 /homepages/20/d34594934/htdocs/tgpbs/public/index.php(66): Zend\Mvc\Application->run()
#19 {main}`

In der Datenbank ist aber alles gespeichert und die Activation aber auf "disabled" gesetzt!

Kann mir bitte geholfen werden denn ich stehe momentan richtig auf dem Schlauch da ja die Saison auch schon begonnen hat!

Gruß tennstar

**Comment by tennstar1** [comment]
Konnte es selbst lösen, ich habe den Ordner Vendor nochmal neu übertragen.
Anscheinend ist hier beim Austausch im November etwas schief gelaufen!

Jetzt funktionierts wieder.

Vielleicht hilfst ja einem anderen!

Gruß tennstar
