### ISSUE TITLE
Fatal Error nach Installation

### ISSUE THREAD

**Issue by jasson09** [tkrebs/ep3-bs#70]
Fatal error: Uncaught Zend\Session\Exception\InvalidArgumentException: 'session.save_path' is not a valid sessions-related ini setting. in xxx/vendor/zendframework/zendframework/library/Zend/Session/Config/SessionConfig.php:90 Stack trace: 
#0 xxx/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php(147): Zend\Session\Config\SessionConfig->setStorageOption('save_path', 'xxx...') 
#1 xxx/vendor/zendframework/zendframework/library/Zend/Session/Config/SessionConfig.php(161): Zend\Session\Config\StandardConfig->setOption('save_path', 'xxx...') 
#2 xxx/vendor/zendframework/zendframework/library/Zend/Session/Config/StandardConfig.php(114): Zend\Session\Config\SessionConfig->setSavePath('xxx...') 
#3 xxx/vendor/zendframework/zendframework/library/Zend/Session/Service/SessionConfigFactory.php(60): Zend\Session\Config\ in xxx/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 946

Die Option mit der Zeile löschen der global.php habe ich versucht:         'save_path' => getcwd() . '/data/session/',

Es kommt aber dennoch die Fehlermeldung. Bei anderen Anwendern dürfte die Lösung jedoch funktioniert haben? :/

**Comment by jasson09** [comment]
Okay, dürfte wohl an den PHP Settings meines Hostinganbieters scheitern, da ich das System bei einem anderen Anbieter erfolgreich getestet habe 👍
